### ISSUE TITLE
Issue with Negative Faction Power Value Post-Migration from v4 to v5

### ISSUE THREAD

**Issue by squawnchy** [Dans-Plugins/Medieval-Factions#1756]
### Discussed in https://github.com/Dans-Plugins/Medieval-Factions/discussions/1753

<div type='discussions-op-text'>

<sup>Originally posted by **squawnchy** July 26, 2023</sup>
Hello Everyone,
<br>
Firstly, I'd like to express my gratitude for this exceptional plugin; it's been a great asset.
<br>
Recently, I encountered an issue following a migration from v4 to v5. For some reason, every faction on my server is now displaying a negative power value. I suspect this may have something to do with the transition from JSON files to a database (DB) system. It looks like there is a pattern in those wrong power values of the factions:
<br>

1. Power Level Faction 1: 0
2. Power Level Faction 2: -5
3. Power Level Faction 3: -10
4. Power Level Faction 4: -15
5. Power Level Faction 5: -20

I've tried to diagnose the issue using DBeaver to connect to the DB and inspect the values, but I was unsuccessful. The following error was returned:
<br>
com.dansplugins.factionsystem.shadow.org.h2.mvstore.tx.VersionedValueType$Factory
<br>
org.h2.jdbc.JdbcSQLNonTransientConnectionException: Datei fehlerhaft beim Lesen des Datensatzes: "C:/Users/Marc/Downloads/tmp/medieval_factions_db.mv.db". Mögliche Lösung: Recovery Werkzeug verwenden
File corrupted while reading record: "C:/Users/Marc/Downloads/tmp/medieval_factions_db.mv.db". Possible solution: use the recovery tool [90030-210]
  Unable to read the page at position 1057180430123996, chunk 3846, offset 271 [2.1.210/6]
  Unable to read the page at position 1057180430123996, chunk 3846, offset 271 [2.1.210/6]
    java.lang.ClassNotFoundException: com.dansplugins.factionsystem.shadow.org.h2.mvstore.tx.VersionedValueType$Factory
    java.lang.ClassNotFoundException: com.dansplugins.factionsystem.shadow.org.h2.mvstore.tx.VersionedValueType$Factory
      com.dansplugins.factionsystem.shadow.org.h2.mvstore.tx.VersionedValueType$Factory
      com.dansplugins.factionsystem.shadow.org.h2.mvstore.tx.VersionedValueType$Factory

<br>
The DB settings remain at their default values.
Does anyone have any insight or advice on how to resolve this issue? Any guidance would be much appreciated.
<br>
MF Version: 5.2.0
<br>
<br>
Best Regards,
Squawnchy</div>

**Comment by squawnchy** [comment]
Nevermind, I uninstalled the plugin.

**Comment by squawnchy** [comment]
Do you need any of my gamefiles?

**Comment by dmccoystephenson** [comment]
What does your config.yml in the 'MedievalFactions' directory look like?

**Comment by squawnchy** [comment]
```yaml
dynmap:
  enableDynmapIntegration: true
version: 5.2.0
language: en-us
database:
  url: jdbc:h2:./medieval_factions_db;AUTO_SERVER=true;MODE=MYSQL;DATABASE_TO_UPPER=false
  dialect: H2
  username: sa
  password: ''
players:
  minPower: -5
  initialPower: 5.0
  maxPower: 125.0
  hoursToReachMaxPower: 25
  hoursToReachMinPower: 72
  powerLostOnDeath: 10.0
  powerGainedOnKill: 10.0
wilderness:
  color: '#3e8e39'
gates:
  minHeight: 3
  maxBlocks: 64
  maxPerFaction: 15
  maxRemoveDistance: 12
pvp:
  enableWartimeBlockDestruction: false
  enabledForFactionlessPlayers: true
  warRequiredForPlayersOfDifferentFactions: true
  friendlyFire: false
  grantPowerToKillerIfVictimHasZeroPower: false
factions:
  titleTerritoryFadeInLength: 5
  titleTerritoryDuration: 20
  titleTerritoryFadeOutLength: 5
  maxMembers: -1
  mobsSpawnInFactionTerritory: true
  allowedMobSpawnReasons:
  - BEEHIVE
  - BREEDING
  - BUILD_IRONGOLEM
  - BUILD_SNOWMAN
  - COMMAND
  - CURED
  - CUSTOM
  - DEFAULT
  - DISPENSE_EGG
  - EGG
  - ENDER_PEARL
  - EXPLOSION
  - FROZEN
  - INFECTION
  - JOCKEY
  - METAMORPHOSIS
  - OCELOT_BABY
  - SHEARED
  - SHOULDER_ENTITY
  - SILVERFISH_BLOCK
  - SLIME_SPLIT
  - SPAWNER
  - SPAWNER_EGG
  - SPELL
  - VILLAGE_DEFENSE
  laddersPlaceableInEnemyFactionTerritory: true
  maxNameLength: '60'
  zeroPowerFactionsGetDisbanded: false
  vassalPowerContributionMultiplier: 0.75
  nonMembersCanInteractWithDoors: false
  maxClaimRadius: false
  limitLand: true
  contiguousClaims: false
  actionBarTerritoryIndicator: true
  titleTerritoryIndicator: false
  allowNeutrality: false
  factionlessFactionName: Factionless
  factionHomeTeleportDelay: 0
  defaults:
    flags:
      protectVillagerTrade: true
      alliesCanInteractWithLand: false
      vassalageTreeCanInteractWithLand: false
      liegeChainCanInteractWithLand: false
      neutral: false
      color: random # Can be hex colours, e.g. '#ffffff', '#ffcc00', etc., or 'random' to choose a random colour
      allowFriendlyFire: false
      acceptBonusPower: true
chat:
  enableDefaultChatFormatting: true
  faction:
    format: '&7[faction] [${factionColor}${faction}&7] [${role}] &f${displayName}:
      ${message}'
  vassals:
    format: '&7[vassals] [${factionColor}${faction}&7] [${role}] &f${displayName}:
      ${message}'
  allies:
    format: '&7[allies] [${factionColor}${faction}&7] [${role}] &f${displayName}:
      ${message}'
duels:
  duration: PT2M
  notificationDistance: 64
dev:
  enableDevCommands: false
```
